In [ ]:
import numpy as np

# 1
arr = np.random.randint(10, 101, size=20)
print(arr)

[14 16 46 23 56 10 13 80 81 85 10 83 90 31 55 63 15 82 51 95]


In [ ]:
# 2
print("First 5 elements:", arr[:5])
print("Last 3 elements:", arr[-3:])
print("Elements at even indices:", arr[::2])

First 5 elements: [14 16 46 23 56]
Last 3 elements: [82 51 95]
Elements at even indices: [14 46 56 13 81 10 90 55 15 51]


In [ ]:
# 3
arr2 = np.random.randint(1, 11, size=20)
print("Second array:", arr2)

print("\nAddition:")
print(arr + arr2)

print("\nSubtraction:")
print(arr - arr2)

print("\nMultiplication:")
print(arr * arr2)

print("\nDivision:")
print(np.round(arr / arr2, 2))

Second array: [ 1  3  9  8  4  4  8  1  1  5  4  5  1  1 10  2 10  9  1  7]

Addition:
[ 15  19  55  31  60  14  21  81  82  90  14  88  91  32  65  65  25  91
  52 102]

Subtraction:
[13 13 37 15 52  6  5 79 80 80  6 78 89 30 45 61  5 73 50 88]

Multiplication:
[ 14  48 414 184 224  40 104  80  81 425  40 415  90  31 550 126 150 738
  51 665]

Division:
[14.    5.33  5.11  2.88 14.    2.5   1.62 80.   81.   17.    2.5  16.6
 90.   31.    5.5  31.5   1.5   9.11 51.   13.57]


In [ ]:
# 4
matrix = arr.reshape(4, 5)
print("\nReshaped 4x5 matrix:")
print(matrix)

print("\nSecond row:", matrix[1])

print("\nLast column:", matrix[:, -1])

print("\nSub-matrix:")
print(matrix[:2, :3])


Reshaped 4x5 matrix:
[[14 16 46 23 56]
 [10 13 80 81 85]
 [10 83 90 31 55]
 [63 15 82 51 95]]

Second row: [10 13 80 81 85]

Last column: [56 85 55 95]

Sub-matrix:
[[14 16 46]
 [10 13 80]]
